dorminhoco test + resolution
podcodar/exercises pull request #17
Opened 2020-12-04 01:02 UTC by nato-re

Adiciona exercício junto a gabarito, com intensão de avaliação para construir enunciado 

Issue: #11

2020-12-05 11:18 UTC, frattezi commented on programming-basics/dorminhoco/test.js
> +  it(`resultado deve ser uma string`, async () => {
acho que aqui deveria ser outra mensagem

2020-12-05 11:23 UTC, frattezi commented
Vamos pensar em como deixar este exercise apenas no template inicial + Uma historinha legal. Vendo o código eu pensei que poderiamos ter uma lista fixa que o user não pode alterar a forma e deve printar cada item em ordem, porém, exigimos uma ordem de impressão diferente da ordem da lista? Não sei ainda não consigo ver esse danado como exercício.

2020-12-05 11:24 UTC, frattezi reviewed
Boa! Vamos conversando e vendo como melhorar

2020-12-05 11:24 UTC, frattezi commented on programming-basics/dorminhoco/main.js
> +const randomDream = (resolve) => () => resolve(dreams[randomPosition])
sempre tentar manter um pattern, se aqui as consts estão em inglês isto deveria ser seguido em todo code, para um lado ou pro outro

2020-12-07 00:34 UTC, marco-souza requested changes

2020-12-07 00:34 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +
vamos evitar linhas vazias

2020-12-07 00:34 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    // const mockDream = jest.fn().mockReturnValue('Ovelhas astronautas')
vamos evitar comentarios no codigo

2020-12-07 00:34 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    expect(typeof sonho).toBe('string');
a gente deveria verificar o valor retornado, não so o tipo

2020-12-07 00:34 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +module.exports = { dorminhoco, sleep, randomDream };
vamos exportar apenas a func `dorminhoco`, dado que so vamos tertar ela, além dela chamar as outras

2020-12-07 00:34 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +
vamos limpar os espaços em brancos pra evitar que o codigo fique "muito espalhado"

2020-12-07 00:34 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +    (resolve) => setTimeout(randomDream(resolve), ms)
Dado que a função de `sleep` também chama o `randomDream`, ou ela deveria:
1. ser mudada de nome (por não fazer apenas um sleep)
2. ou isolar as partes, chamando sleep e depois o randomDream

```js
const sleep => ms => setTimeout(Promise.resolve(), ms)

await sleep(2000)
const sonho = randomDream() 
```

pessoalmente acho a opção 2 mais elegante

2020-12-07 00:34 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +const dreams = [
talvez devessemos colocar os sonhos como parametro da função principal, para facilitar os testes

2020-12-07 01:59 UTC, nato-re commented on programming-basics/dorminhoco/main.js
> +const dreams = [
show, gostei da ideia

2020-12-07 01:59 UTC, nato-re commented on programming-basics/dorminhoco/main.js
> +const randomDream = (resolve) => () => resolve(dreams[randomPosition])
mara <3

2020-12-07 02:01 UTC, nato-re commented on programming-basics/dorminhoco/main.js
> +    (resolve) => setTimeout(randomDream(resolve), ms)
Entendi o padrão, mas estou com dificuldades de aplicar no exercicío

2020-12-07 02:04 UTC, nato-re commented on programming-basics/dorminhoco/main.js
> +module.exports = { dorminhoco, sleep, randomDream };
faz sentido, junto com a dream list passada como parâmentro vai ficar shop de testar

2020-12-07 02:04 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +    // const mockDream = jest.fn().mockReturnValue('Ovelhas astronautas')
Realmente, já tá no comitão bomba, foi só desatenção, mt grato <3

2020-12-07 02:04 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +    expect(typeof sonho).toBe('string');
tá ainda tô pensando como fazer, mas concordo contigo, vai ficar mais robusto

2020-12-07 02:04 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +  it(`resultado deve ser uma string`, async () => {
mara, segue no comitão bomba anexado no email <3

2020-12-07 02:04 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +
comitão bomba anexa clean dos espaços no email

2020-12-07 02:34 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +    expect(setTimeout).toBeCalledWith(expect.any(Function), 42);
função chamada com undefined, não entendi o processo

2020-12-07 02:34 UTC, nato-re commented on programming-basics/dorminhoco/main.js
> +const dreamList = [
ainda estou pensando em como fazer com a lista sem aleatoriaedade

2020-12-07 14:26 UTC, frattezi commented on programming-basics/dorminhoco/test.js
> +    expect(setTimeout).toBeCalledWith(expect.any(Function), 42);
seu teste não é async, acredito que isto está impactando sua leitura

2020-12-07 14:27 UTC, frattezi commented on programming-basics/dorminhoco/main.js
> +const dreamList = [
acho que fica mais fácil. talvez, vamos tentar moldar a ordem do problema de uma vez antes de ir para implementação

2020-12-08 16:05 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +    expect(setTimeout).toBeCalledWith(expect.any(Function), 42);
faz mt sentido :D
vou implementar!

2020-12-12 13:31 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +const dreamList = [
aleatoriedade é o que torna os testes mais fracos, dado que você pode ter resultados diferentes para cada vez que vc rodar os testes, acho que seria bom simplificar essa implementação mesmo

2020-12-12 13:47 UTC, marco-souza requested changes

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +const dreamList = [
Uma possibilidade é mockar a função 'Math.random()'

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +  const promisedDream = new Promise((resolve) =>
A gente não precisa disso.

vc ta misturando callback com async/await, sendo que ambos server ao mesmo proposito, fazer uma chamada no asincrona.


recomendo:
1. remover o cb do sleep
2. chamar a função randomDream depois de um await

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +  const dream = await promisedDream;
```suggestion
const sleep = (ms) => new Promise(res => setTimeout(cb, res);
 
export const dorminhoco = async (milliseconds, dreamList) => {
  await sleep(milliseconds)
  const dream = randomDream()
```

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +const main = require('./main');
vamos evitar require em nossos projetos em pro da sintaxe mais recente e recomendada de `import { dorminhoco } from './main'`

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +module.exports = { dorminhoco };
Vamos evitar esse export

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +  });
coloque espaços entre os casos de testes

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +  const dreamMock = ['não lembro do sonho'];
Declare essa variavel fora do describe, por padrão, geralmente declaramos constantes imutáveis no escopo raiz como uma boa prática

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +});
Não temos casos de testes com listas vazias.

quando fazemos unit teste temos que validar caminhos felizes e caminhos tristes, como por exemplo:
- lista vazia
- string no lugar da lista
- lista `undefined`
- so on

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    expect(setTimeout).toBeCalledWith(expect.any(Function), 42);
+1

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    expect(setTimeout).toBeCalledTimes(1);
não estamos validando a função setTimeout, ela já é testada pelo core team do JS.

O que queremos testar é a função dorminhoco e seus retornos

2020-12-12 13:47 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +  it(`resultado deve ser uma string`, async () => {
Este caso de teste é um bom exemplo de caminho feliz, agora precisamos fazer os testes para caminhos triste

2020-12-19 14:27 UTC, frattezi commented on programming-basics/dorminhoco/main.js
> +const dreamList = [
+1

2020-12-21 19:33 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +});
Acho válido, mas estou tentando testar com o node assim:
`dorminhoco(42, [])`
e dá isso:
`SyntaxError: Unexpected token 'export'`

2020-12-21 19:34 UTC, nato-re commented on programming-basics/dorminhoco/main.js
> +  const dream = await promisedDream;
gostei, implementei parecido no commit

2020-12-21 19:34 UTC, nato-re commented on programming-basics/dorminhoco/main.js
> +  const promisedDream = new Promise((resolve) =>
fiz no commit, acho que ficou de acordo com suas colocações

2020-12-21 19:36 UTC, nato-re commented on programming-basics/dorminhoco/main.js
> +const dreamList = [
muito bem, vou implementar, junto com os testes dos caminhos feios aushda <3

2020-12-25 11:06 UTC, marco-souza requested changes
Bom trabalho, a função já ta bem melhor! :+1:

Alguns pontos de atenção:
- não devemos enviar a resolução do exercicio, apenas os testes, a descrição e algumas funções uteis para resolver o problema
- Os nomes dos testes precisam ser mais descritivos, pois é onde os estudantes da podcodar vão validar suas resoluções. 
- Precisamos de um padrão de nome para todos os casos de teste para facilitar a leitura de quem for resolver
- Temos de prestar atenção nos asserts, para garantirmos que estamos validando o que queremos de fato, e não fazendo validacões que envolvem transformação/coerção de tipos, e funções nativas do JS.

PS: foi mal os longos reviews, não é nada pessoal, hahaha, só estou tentando manter o exercicio dentro dos nossos padrões (que ainda precisam ser melhor definidos, mas já conseguimos dar dicas de boas práticas e tals...) :smiley:

2020-12-25 11:06 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    expect(dream).not.toEqual([])
Esse assert não ta legal, o retorno da func é uma string, pq estamos comparando se ele não é um array?

2020-12-25 11:06 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +});
node por padrão não reconhece o `exoprt`, precisamos do babel para tal. No entanto, o Jest deveria lidar com isso pra gente.

2020-12-25 11:06 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    expect(!dream).toBe(false)
Esse assert também ta estranho, !dream === false? não é a mesma coisa de verificar se dream é `true`?

2020-12-25 11:06 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +  it(`checa se sonho tem retorno válido`, async () => {
Acho que os nomes dos casos de testes precisam ser mais descritivos como `"Quando a lista de sonhos é vazia, o retorno deve ser inválido"` ou algo assim

2020-12-25 11:06 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    const dream = dorminhoco(42, dreamMock);
Deveriamos ter alguns tratamentos de if, para lidar com lista vazia. Do jeito que está rodando, mesmo que uma lista vazia seja recebida, esperamos o timeout antes de dar um erro na hora do retorno.

É bom SEMPRE validar suas entradas antes de executar qualquer coisa, não so em JS, mas principalmente em JS, que tem uma tipagem fraca e que faz coerção de tipos, o que gera muita merdas

2020-12-25 11:06 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    expect(!dream).toBe(false)
Acho que ambos os asserts precisam ser mais acertivos

2020-12-25 11:06 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +});
O ideal é rodar com jest e ir testando

2020-12-30 20:09 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +    expect(dream).not.toEqual([])
Quanto maior o CR, melhor <3
Esse aí já foi implementada

2020-12-30 20:10 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +    expect(!dream).toBe(false)
done, acho válida a pontuação da redundância, grato pela atenção

2020-12-30 20:11 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +  it(`checa se sonho tem retorno válido`, async () => {
Isso ainda não foi implementado, mas já está em mente

2020-12-30 20:14 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +    const dream = dorminhoco(42, dreamMock);
isso não ficou claro para mim, podemos conversar mais sobre?
Um tratamento de entrada seria como nesse caso?
acabei mudando a abordagem tô meio confuso em como encaixar sua sugestão

2020-12-30 20:21 UTC, nato-re commented on programming-basics/dorminhoco/test.js
> +    expect(dream).not.toEqual([])
O que cê acha do exercício com o viés abaixo? 
```js
// Crie código dentro da função dorminhoco para que ela retorne uma promessa, onde depois de x `miliseconds` um sonho aleatório seja retornado 
const randomDream = (dreams) =>
  dreams[Math.floor(Math.random() * dreams.length)];

export const dorminhoco = async (milliseconds, dreamList) => {
};
```
os pontos abaixo já estão na minha mente para finalizar esse exercício:
- melhor descrição dos testes
- descrição do objetivo do exercício 
- fomatar o `main.js` de maneira que fique pronto para uso
Existe mais algum ponto de atenção ou dica para execução, meu querido?

2021-01-03 16:05 UTC, marco-souza requested changes
Boa, estamos chegando lá! :cat: 

Próximos passos ao meu ver seriam
- [ ] sugestões da revisão atual
- [ ] remover resolução da `main.js`
- [ ] Adicionar descrição do problema no `README.md`
- [ ] rodar `prettier` e/ou `eslint` para mantar os estilos homogêneos
- [ ] melhor descrição dos testes
- [ ] Refatorar os commits com `git rebase -i` para entrar no padrão definido pelo @frattezi

2021-01-03 16:05 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    jest.spyOn(global.Math, 'random').mockReturnValue(0);
Boa, mandou bem no mock!

Uma dúvida: precisamos de dar `spyOn` sempre antes de cada test case? Ou podemos usá-lo apenas uma vez e aceitar que o `jest.clearAllMocks()` vai limpar o mock pra gente?

2021-01-03 16:05 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    return dorminhoco(42, dreamMock).then((dream) => {
Acho que seria mais elegante usar async/await para lidar com promises

2021-01-03 16:05 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +      expect(typeof dream).toBe('string');
Não precisamos validar o type, dado que estamos validando o valor + tipo logo abaixo

2021-01-03 16:05 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    return dorminhoco(42, 'nao sou um array').then((dream) => {
me parece estranho rodar com uma string. Não deveriamos rodar apenas com array? Mesmo o JS tratando Array como String, acho que seria melhor nao rodar para strings

```
# input:
42 "minha string'

# output
undefined
```

2021-01-03 16:05 UTC, marco-souza commented on programming-basics/dorminhoco/test.js
> +    dorminhoco(42, dreamMock);
dado que o dominhoco é uma promise, precisamos de dar `await` aqui para aguardar a execução. Do jeito que está vai passar por causa do asset feito abaixo, que só valida se `setTimeout` foi chamado, mas num teste real, precisamos aguardar as promisses se resolverem antes de validar o retorno

2021-01-03 16:05 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +  return dream;
```suggestion
  if (Array.isArray(dreamList)) 
    return // early return to avoid extra processing
  await sleep(milliseconds)
  return randomDream(dreamList)
```

2021-01-03 16:05 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +  return dream;
Simplificando a implementação

2021-01-03 16:05 UTC, marco-souza commented on programming-basics/dorminhoco/main.js
> +  return dream;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray talvez seja bom mencionar isso na descrição do problema

2025-11-01 22:23 UTC, closed without merging