add-soma-fatoriais
podcodar/exercises pull request #26
Opened 2021-01-26 12:18 UTC by anacaldasm

Adicionar novo exercício ao repo da PodCodar

##Modificações

Novo arquivo main.js test.js e README.md com as orientações para a resolução do exercício.

2021-01-26 12:31 UTC, frattezi commented on programming-basics/soma-fatoriais/README.md
> +Leia dois valores inteiros M e N indefinidamente. A cada leitura, calcule e escreva a soma dos fatoriais de cada um dos valores lidos. Utilize uma variável apropriada, pois cálculo pode resultar em u
Podemos adaptar um pouco este texto, para falar algo como:
"A partir de dois valores inteiros M e N seu programa deve retornar ....."

2021-01-26 12:40 UTC, frattezi reviewed
Muito BOM! Emocionado com a contribuição pro exercises!

2021-01-26 12:40 UTC, frattezi commented on programming-basics/soma-fatoriais/main.js
> +  export default somaFatoriais;
Adicione uma linha ao fim do arquivo, parece bobo mas é importante!

https://pt.stackoverflow.com/questions/272449/por-que-inserir-uma-linha-em-branco-no-final-do-c%C3%B3digo#:~:text=1%20Resposta&text=Ao%20trabalhar%20com%20ferramentas%20padr%C3%B5es,final%2C%20alguns%20problemas%20podem%20aparecer.&text=Em%20sistemas%20n%C3%A3o%20comp%C3%A1tiveis%20com,terminados%20com%20uma%20nova%20linha.

2021-01-26 12:40 UTC, frattezi commented on programming-basics/soma-fatoriais/test.js
> +}
Same same

2021-01-26 12:40 UTC, frattezi commented on programming-basics/soma-fatoriais/test.js
> +      it(`Para as entradas 4 e 5 o programa deve retornar 144`, () => {
Aqui tem um errinho de formatação, este `IT` está com 1 tab a mais do que deveria.

Tente instalar o prettier no seu vscode, ele vai fazer este trabalho por você.
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2021-01-26 12:40 UTC, frattezi commented on programming-basics/soma-fatoriais/test.js
> +      });
Aqui também tem 1 tab a mais. Perceba que a chave `}` que fecha o `if` devem sempre estar no mesmo nível de identação. Pode considerar isso como uma "regrinha de ouro"

2021-01-26 12:40 UTC, frattezi commented on programming-basics/soma-fatoriais/test.js
> +      });
E não apenas para o `if` mas para qualquer função que abra um escopo, exemplo:

```
qualquerCoisaQueAbbraChaves() {
    outraCoisaQueAbraChaves(){
    }
}
```
Perceba, sempre fechando a chave no mesmo nível onde a definição começa

2021-01-27 02:25 UTC, anacaldasm commented on programming-basics/soma-fatoriais/main.js
> +  export default somaFatoriais;
alterações feitas!

2021-01-27 12:18 UTC, frattezi reviewed
Tamo quase!

2021-01-27 12:18 UTC, frattezi commented on programming-basics/soma-fatoriais/test.js
> +
KKKK eu sei que é chato, mas faltou esse enter aqui, pode remover.

E acho que deveria ter uma linha 16 em branco

2021-01-28 21:58 UTC, marco-souza requested changes
Apenas algumas alterações pequenas, mas foi um ótimo trabalho num geral

2021-01-28 21:58 UTC, marco-souza commented on programming-basics/soma-fatoriais/main.js
> +
isso ta estranho, confere se não tem um espaços

2021-01-28 21:58 UTC, marco-souza commented on programming-basics/soma-fatoriais/test.js
> +      expect(somaFatoriais(2,2)).toBe(4);
achoo que o espaçamento ta errado

2021-01-28 21:58 UTC, marco-souza commented on programming-basics/soma-fatoriais/test.js
> +      expect(somaFatoriais(2,2)).toBe(4);
identação

2021-02-01 16:39 UTC, frattezi commented on programming-basics/soma-fatoriais/test.js
> +}
Tem um errinho aqui
```suggestion
});
```

2021-02-01 16:40 UTC, frattezi commented on programming-basics/soma-fatoriais/test.js
> +}
Apesar de não estar aparecendo, existe uma linha ao fim do arquivo, parece algo do git

2021-02-02 14:25 UTC, frattezi approved these changes
( •_•)
( •_•)>⌐■-■
(⌐■_■) #Yeeeaaahhh

2021-02-05 13:01 UTC, marco-souza requested changes
Muito bom! dois small fixes pra terminar

2021-02-05 13:01 UTC, marco-souza commented on .prettierrc
> +{
Acho que podemos remover esse arquivo, ou mover ele pra raiz do projeto

2021-02-05 13:01 UTC, marco-souza commented on programming-basics/soma-fatoriais/test.js
> +
Eu removeria essa linha, mas é bobagem minha 😹

2021-02-26 21:50 UTC, marco-souza approved these changes

2021-02-26 21:51 UTC, merged