feat: adiciona exercicio cofrinhos do jorel
podcodar/exercises pull request #27
Opened 2021-02-12 01:00 UTC by frattezi

Adiciona o exercício cofrinhos do Jorei, carece de testes.

2021-02-12 12:28 UTC, frattezi commented on programming-basics/cofrinhos-do-jorel/README.md
> +[{'benedito': '30'}, {'marquinhos': '50'}, {'bruninho': '25'}]
Entendi o por que da lista @marco-souza você não quer que eles tenham de usar propriedades como keys() ou algo assim? Bem podemos voltar para lista com 2 strings mas acho que o desafio da sobrecarca de operadores ainda interessante.

2021-02-26 21:56 UTC, fmagesty commented on programming-basics/cofrinhos-do-jorel/README.md
> +[{'benedito': '30'}, {'marquinhos': '50'}, {'bruninho': '25'}]
oi

2021-02-28 13:50 UTC, marco-souza requested changes
Boa demais, mandou bem! Deixei apenas alguns comentários menores de boas práticas e uns pontos sobre testes :smile:

2021-02-28 13:50 UTC, marco-souza commented on programming-basics/cofrinhos-do-jorel/README.md
> +[{'benedito': '30'}, {'marquinhos': '50'}, {'bruninho': '25'}]
Por isso tbm, mas eu acho que é isso mesmo, temos que trabalhar cada vez com o parsing de dados, dado que essa é a tarefa mais recorrente no desenvolvimento web

2021-02-28 13:50 UTC, marco-souza commented on programming-basics/cofrinhos-do-jorel/test.js
> +  const entrada1 = [
Estamos usando nomes de variaveis em inglês né?

Acho que é uma boa pratica, por ingles ser a linguagem "padrão"

2021-02-28 13:50 UTC, marco-souza commented on programming-basics/cofrinhos-do-jorel/test.js
> +    expect(caixaEletronico(entrada1)).toBe(saida1);
precisamos usar `toStrictEqual` quando formos comparar objetos complexos, como lista e objetos.

https://jestjs.io/docs/en/expect#tostrictequalvalue

2021-02-28 13:50 UTC, marco-souza commented on programming-basics/cofrinhos-do-jorel/test.js
> +
Devemos testar mais cosias, como valores inesperados, lista vazia, receber uma lista de transacões inválidas.


A ideia dos testes é cobrir todos os casos de canto, ou seja, situações aonde não está claro o comportamento da função. Com isso conseguimos cobrir bem os testes pro nosso problema

2021-04-01 14:17 UTC, frattezi commented on programming-basics/cofrinhos-do-jorel/test.js
> +  const entrada1 = [
topo, vou padronizar

2021-04-01 14:17 UTC, frattezi commented on programming-basics/cofrinhos-do-jorel/test.js
> +    expect(caixaEletronico(entrada1)).toBe(saida1);
esses testes ai tavam falando não, subindo new version

2021-04-01 23:25 UTC, merged